--! Previous: sha1:82dd9fd23ac31f5165f7ac4ff7414079cceaa65c
--! Hash: sha1:59171950d15d2f1df34f59959090196480343472

drop table if exists chat_message ;

do $$
  begin

ALTER TABLE
  public.completed_workout
ALTER COLUMN
  id DROP DEFAULT;
DROP SEQUENCE public.completed_workout_id_seq;
ALTER TABLE
  public.completed_workout
ALTER COLUMN
  id
ADD
  GENERATED BY DEFAULT AS IDENTITY;
  exception 
    when sqlstate '42601' then
      raise notice 'Already replaced identity';

end $$;

do $$
  begin

ALTER TABLE
  public.completed_workout_exercise
ALTER COLUMN
  id DROP DEFAULT;
DROP SEQUENCE public.completed_workout_exercise_id_seq;
ALTER TABLE
  public.completed_workout_exercise
ALTER COLUMN
  id
SET
  DATA TYPE INT;
ALTER TABLE
  public.completed_workout_exercise
ALTER COLUMN
  id
ADD
  GENERATED BY DEFAULT AS IDENTITY;
  exception 
    when sqlstate '42601' then
      raise notice 'Already replaced identity';
end $$;

do $$
  begin
ALTER TABLE
  public.workout_plan
ALTER COLUMN
  id DROP DEFAULT;
DROP SEQUENCE public.workout_plan_id_seq1;
ALTER TABLE
  public.workout_plan
ALTER COLUMN
  id
ADD
  GENERATED BY DEFAULT AS IDENTITY;
  exception 
    when sqlstate '42601' then
      raise notice 'Already replaced identity';
end $$;



do $$
  begin
ALTER TABLE
  public.workout_plan_day
ALTER COLUMN
  id DROP DEFAULT;
DROP SEQUENCE public.workout_plan_id_seq;
ALTER TABLE
  public.workout_plan_day
ALTER COLUMN
  id
ADD
  GENERATED BY DEFAULT AS IDENTITY;
  exception 
    when sqlstate '42601' then
      raise notice 'Already replaced identity';
end $$;

do $$
  begin
ALTER TABLE
  public.exercise
ALTER COLUMN
  id DROP DEFAULT;
DROP SEQUENCE public.exercise_id_seq;
ALTER TABLE
  public.exercise
ALTER COLUMN
  id
ADD
  GENERATED BY DEFAULT AS IDENTITY;
  exception 
    when sqlstate '42601' then
      raise notice 'Already replaced identity';
end $$;


do $$
  begin

ALTER TABLE
  public.exercise_alias
ALTER COLUMN
  id
  set not null;

ALTER TABLE
  public.exercise_alias
ALTER COLUMN
  id
ADD
  GENERATED BY DEFAULT AS IDENTITY;
  exception 
    when sqlstate '55000' then
      raise notice '';
end $$;
