const fetch = require("node-fetch");
const https = require("https");
const rootCas = require("ssl-root-cas").create();
const path = require("path");
rootCas.addFile(path.resolve(__dirname, "intermediate.pem"));
const httpsAgent = new https.Agent({ ca: rootCas });
const cheerio = require("cheerio");
const fs = require("fs");

var slugs = [
  "bench-press",
  "squat",
  "deadlift",
  "shoulder-press",
  "barbell-curl",
  "front-squat",
  "bent-over-row",
  "incline-bench-press",
  "hex-bar-deadlift",
  "sumo-deadlift",
  "hip-thrust",
  "romanian-deadlift",
  "military-press",
  "seated-shoulder-press",
  "close-grip-bench-press",
  "ez-bar-curl",
  "barbell-shrug",
  "lying-tricep-extension",
  "strict-curl",
  "decline-bench-press",
  "zercher-squat",
  "pendlay-row",
  "box-squat",
  "t-bar-row",
  "preacher-curl",
  "paused-bench-press",
  "rack-pull",
  "upright-row",
  "floor-press",
  "barbell-reverse-lunge",
  "wrist-curl",
  "stiff-leg-deadlift",
  "barbell-calf-raise",
  "bulgarian-split-squat",
  "barbell-lunge",
  "tricep-extension",
  "good-morning",
  "split-squat",
  "pause-squat",
  "bodyweight-calf-raise",
  "safety-bar-squat",
  "neck-curl",
  "deficit-deadlift",
  "log-press",
  "reverse-barbell-curl",
  "wide-grip-bench-press",
  "sumo-squat",
  "single-leg-deadlift",
  "neck-extension",
  "barbell-glute-bridge",
  "reverse-grip-bench-press",
  "reverse-wrist-curl",
  "pause-deadlift",
  "jm-press",
  "ab-wheel-rollout",
  "bench-pull",
  "snatch-grip-deadlift",
  "bench-pin-press",
  "behind-the-neck-press",
  "barbell-hack-squat",
  "landmine-press",
  "landmine-squat",
  "pin-squat",
  "snatch-deadlift",
  "barbell-front-raise",
  "belt-squat",
  "reverse-curl",
  "yates-row",
  "walking-lunge",
  "machine-shrug",
  "jefferson-squat",
  "behind-the-back-barbell-shrug",
  "barbell-power-shrug",
  "bent-arm-barbell-pullover",
  "cheat-curl",
  "donkey-calf-raise",
  "viking-press",
  "spider-curl",
  "shoulder-pin-press",
  "barbell-pullover",
  "wall-ball",
  "standing-leg-curl",
  "single-leg-romanian-deadlift",
  "z-press",
  "jefferson-deadlift",
  "pull-ups",
  "push-ups",
  "dips",
  "chin-ups",
  "bodyweight-squat",
  "sit-ups",
  "handstand-push-ups",
  "crunches",
  "back-extension",
  "one-arm-push-ups",
  "pistol-squat",
  "diamond-push-ups",
  "single-leg-squat",
  "muscle-ups",
  "glute-bridge",
  "lunge",
  "burpees",
  "neutral-grip-pull-ups",
  "hanging-leg-raise",
  "glute-ham-raise",
  "russian-twist",
  "bench-dips",
  "one-arm-pull-ups",
  "lying-leg-raise",
  "inverted-row",
  "hanging-knee-raise",
  "australian-pull-ups",
  "ring-muscle-ups",
  "reverse-lunge",
  "toes-to-bar",
  "star-jump",
  "squat-thrust",
  "squat-jump",
  "side-lunge",
  "side-crunch",
  "roman-chair-side-bend",
  "pike-push-up",
  "mountain-climbers",
  "leg-lift",
  "jumping-jack",
  "jump-squat",
  "incline-push-up",
  "incline-bench-sit-up",
  "hip-extension",
  "flutter-kick",
  "floor-hip-extension",
  "floor-hip-abduction",
  "decline-push-up",
  "decline-crunch",
  "clap-pull-up",
  "bicycle-crunch",
  "sissy-squat",
  "close-grip-push-up",
  "nordic-hamstring-curl",
  "reverse-crunches",
  "ring-dips",
  "power-clean",
  "snatch",
  "clean",
  "push-press",
  "clean-and-jerk",
  "thruster",
  "clean-and-press",
  "hang-clean",
  "overhead-squat",
  "hang-power-clean",
  "power-snatch",
  "push-jerk",
  "split-jerk",
  "clean-pull",
  "dumbbell-snatch",
  "muscle-snatch",
  "dumbbell-push-press",
  "dumbbell-high-pull",
  "dumbbell-hang-clean",
  "snatch-pull",
  "clean-high-pull",
  "dumbbell-bench-press",
  "dumbbell-curl",
  "dumbbell-shoulder-press",
  "incline-dumbbell-bench-press",
  "dumbbell-row",
  "dumbbell-lateral-raise",
  "hammer-curl",
  "dumbbell-fly",
  "goblet-squat",
  "dumbbell-bulgarian-split-squat",
  "dumbbell-shrug",
  "dumbbell-tricep-extension",
  "dumbbell-floor-press",
  "lying-dumbbell-tricep-extension",
  "dumbbell-lunge",
  "dumbbell-concentration-curl",
  "dumbbell-squat",
  "arnold-press",
  "dumbbell-pullover",
  "dumbbell-reverse-fly",
  "dumbbell-front-raise",
  "renegade-row",
  "dumbbell-side-bend",
  "dumbbell-calf-raise",
  "dumbbell-deadlift",
  "chest-supported-dumbbell-row",
  "dumbbell-wrist-curl",
  "dumbbell-z-press",
  "dumbbell-bench-pull",
  "dumbbell-romanian-deadlift",
  "dumbbell-tricep-kickback",
  "tate-press",
  "incline-dumbbell-fly",
  "dumbbell-upright-row",
  "incline-dumbbell-curl",
  "dumbbell-preacher-curl",
  "decline-dumbbell-bench-press",
  "close-grip-dumbbell-bench-press",
  "incline-hammer-curl",
  "dumbbell-incline-y-raise",
  "seated-dumbbell-tricep-extension",
  "seated-dumbbell-shoulder-press",
  "dumbbell-reverse-wrist-curl",
  "dumbbell-front-squat",
  "decline-dumbbell-fly",
  "dumbbell-external-rotation",
  "bent-over-dumbbell-row",
  "seated-dumbbell-curl",
  "zottman-curl",
  "sled-leg-press",
  "horizontal-leg-press",
  "leg-extension",
  "chest-press",
  "machine-chest-fly",
  "lying-leg-curl",
  "machine-shoulder-press",
  "seated-leg-curl",
  "seated-calf-raise",
  "machine-tricep-press",
  "hack-squat",
  "machine-calf-raise",
  "machine-bicep-curl",
  "smith-machine-squat",
  "machine-row",
  "vertical-leg-press",
  "close-grip-lat-pulldown",
  "smith-machine-bench-press",
  "seated-dip-machine",
  "machine-lateral-raise",
  "machine-reverse-fly",
  "hip-abduction",
  "sled-press-calf-raise",
  "single-leg-press",
  "hip-adduction",
  "machine-seated-crunch",
  "machine-back-extension",
  "smith-machine-shrug",
  "single-leg-seated-calf-raise",
  "machine-tricep-extension",
  "lat-pulldown",
  "tricep-pushdown",
  "seated-cable-row",
  "tricep-rope-pushdown",
  "cable-fly",
  "face-pull",
  "reverse-grip-lat-pulldown",
  "cable-bicep-curl",
  "cable-crossover",
  "straight-arm-pulldown",
  "cable-overhead-tricep-extension",
  "cable-woodchoppers",
  "cable-pull-through",
  "cable-lateral-raise",
  "reverse-grip-tricep-pushdown",
  "cable-crunch",
  "one-arm-cable-bicep-curl",
  "high-pulley-crunch",
  "standing-cable-crunch",
  "overhead-cable-curl",
  "one-arm-seated-cable-row",
  "one-arm-pulldown",
  "lying-cable-curl",
  "incline-cable-curl",
  "cable-upright-row",
  "cable-shrug",
  "cable-leg-extension",
  "cable-external-rotation",
  "behind-the-back-cable-curl",
  "cable-reverse-fly",
  "cable-kickback",
];

dict = {};

async function fetch_exercises() {
  for (slug of slugs) {
    await fetch(`https://strengthlevel.com/strength-standards/${slug}/kg`, {
      agent: httpsAgent,
      headers: {
        accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "accept-language": "en-US,en;q=0.9,fi;q=0.8",
        "cache-control": "max-age=0",
        "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "same-origin",
        "sec-fetch-user": "?1",
        "upgrade-insecure-requests": "1",
        cookie: "strengthsession=shi48lk0a01dqv02hin1duu5uf; strengthlogin=51140a20-1740-4593-a269-0f9d0cf5ee26%3Ae76f0b3b-fdec-4894-a6b3-280732bac720",
      },
      referrer: "https://strengthlevel.com/strength-standards",
      referrerPolicy: "no-referrer-when-downgrade",
      body: null,
      method: "GET",
      mode: "cors",
    })
      .then((response) => {
        if (response.ok) {
          return response.text();
        }
      })
      .then((text) => {
        $ = cheerio.load(text);
        const result = $("div[class=section-box] > h2[id=standardsMale]").parent().find("tbody > tr > td").last().text()
        var match = result.match(/\d+/);
        dict[slug] = match[0];
        console.log(`${slug}: ${match[0]}`)
      });
  }
  // convert JSON object to string
  const data = JSON.stringify(dict);
  fs.writeFile("exercises.json", data, (err) => {
    if (err) {
      throw err;
    }
    console.log("JSON data is saved.");
  });
}
fetch_exercises();
